import { QSO, logBook } from '../LogBook';

export interface CloudLogConfig {
  wavelogEnabled: boolean;
  wavelogUrl: string;
  wavelogApiKey: string;
  wavelogStationProfileId: string;
}

export class CloudLogService {
  /**
   * Generates a simple ADIF string for a single QSO to be submitted to Cloudlog/Wavelog.
   */
  private static generateAdif(qso: QSO): string {
    let adif = "Generated by WebFT8 <adif_ver:5>3.1.4 <eoh>\n";
    let row = "";

    const processField = (field: string, value: string | number | undefined) => {
      if (value !== undefined && value !== null && value !== "") {
        const strVal = String(value);
        row += `<${field}:${strVal.length}>${strVal} `;
      }
    };

    processField("call", qso.call);
    processField("qso_date", qso.qso_date);
    processField("time_on", qso.time_on);
    processField("band", qso.band);
    processField("freq", qso.freq);
    processField("mode", qso.mode || "FT8");
    if (qso.submode) {
      processField("submode", qso.submode);
    }
    processField("rst_sent", qso.rst_sent);
    processField("rst_rcvd", qso.rst_rcvd);
    processField("gridsquare", qso.gridsquare);

    row += "<eor>\n";
    adif += row;
    return adif;
  }

  /**
   * Cleans the user provided URL to prevent double slashes before /api/qso
   */
  private static getBaseUrl(url: string): string {
    return url.replace(/\/+$/, '');
  }

  /**
   * Sends a single record. Returns success boolean.
   */
  static async pushSingleQSO(qso: QSO, config: CloudLogConfig): Promise<boolean> {
    if (!config.wavelogEnabled || !config.wavelogUrl || !config.wavelogApiKey) {
      return false;
    }

    try {
      const targetUrl = `${this.getBaseUrl(config.wavelogUrl)}/api/qso`;
      // We route the request through the local proxy to bypass CORS
      const endpoint = '/api/log-proxy';
      
      const payload = {
        targetUrl: targetUrl,
        key: config.wavelogApiKey,
        api_key: config.wavelogApiKey,
        station_profile_id: config.wavelogStationProfileId,
        type: 'adif',
        string: this.generateAdif(qso),
        adif: this.generateAdif(qso)
      };

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify(payload)
      });

      if (response.ok) {
        return true;
      }
      return false;
    } catch (e) {
      console.error('Failed to push QSO to Cloudlog/Wavelog', e);
      return false;
    }
  }

  /**
   * Fetches all local database entries where synced === false.
   * Loops through them asynchronously, attempts to push them via pushSingleQSO,
   * and updates their local DB status to true upon success.
   */
  static async syncOfflineQueue(config: CloudLogConfig): Promise<void> {
    if (!config.wavelogEnabled || !config.wavelogUrl || !config.wavelogApiKey) {
      return;
    }

    try {
      const qsos = await logBook.getAllQSOs();
      const unsyncedQsos = qsos.filter((q) => q.synced === false);

      for (const qso of unsyncedQsos) {
        const success = await this.pushSingleQSO(qso, config);
        if (success && qso.id !== undefined) {
          await logBook.updateQSO({ ...qso, synced: true });
        }
      }
    } catch (e) {
      console.error('Failed to sync offline queue', e);
    }
  }

  /**
   * Performs a mock/lightweight validation fetch to verify credentials.
   */
  static async testWavelogConnection(url: string, apiKey: string, stationProfileId: string): Promise<{ success: boolean; message: string }> {
    try {
      const targetUrl = `${this.getBaseUrl(url)}/api/qso`;
      // Route test through the proxy to bypass CORS
      const endpoint = '/api/log-proxy';
      
      const payload = {
        targetUrl: targetUrl,
        key: apiKey,
        api_key: apiKey,
        station_profile_id: stationProfileId,
        type: 'adif',
        string: "Generated by WebFT8 <adif_ver:5>3.1.4 <eoh>\n<eor>\n",
        adif: "Generated by WebFT8 <adif_ver:5>3.1.4 <eoh>\n<eor>\n"
      };

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify(payload)
      });

      if (response.ok) {
        // Look for typical json response from Wavelog/Cloudlog
        try {
          const data = await response.json();
          // API returns e.g. { "status": "created" } or { "status": "failed", "reason": "invalid api key" }
          if (data.status === 'failed') {
             return { success: false, message: `API Error: ${data.reason || JSON.stringify(data)}` };
          }
        } catch(err) {
          // not json? just fallback to ok
        }
        return { success: true, message: 'Connection successful' };
      }
      return { success: false, message: `HTTP Error ${response.status}: ${response.statusText}` };
    } catch (e: any) {
      console.error('Failed to test Wavelog connection', e);
      // Detailed error for CORS or mixed content
      let msg = e.message || String(e);
      if (msg.includes('Failed to fetch')) {
        msg = 'Failed to fetch (Check CORS/Mixed Content. If using HTTPS app, use HTTPS Server URL)';
      }
      return { success: false, message: msg };
    }
  }
}
