export interface QSO {
    id?: number;
    call: string;
    qso_date: string;
    time_on: string;
    band: string;
    freq: number;
    mode: string;
    submode: string;
    rst_sent: string;
    rst_rcvd: string;
    gridsquare: string;
    timestamp: number;
}

export class LogBook {
    private dbName = 'FT8LogDB';
    private storeName = 'qsos';
    private version = 1;
    private db: IDBDatabase | null = null;

    async init(): Promise<void> {
        if (this.db) return;
        return new Promise((resolve, reject) => {
            const request = indexedDB.open(this.dbName, this.version);
            request.onupgradeneeded = (e) => {
                const db = (e.target as IDBOpenDBRequest).result;
                if (!db.objectStoreNames.contains(this.storeName)) {
                    const store = db.createObjectStore(this.storeName, { keyPath: 'id', autoIncrement: true });
                    store.createIndex('timestamp', 'timestamp', { unique: false });
                }
            };
            request.onsuccess = (e) => {
                this.db = (e.target as IDBOpenDBRequest).result;
                resolve();
            };
            request.onerror = (e) => reject((e.target as IDBOpenDBRequest).error);
        });
    }

    async logQSO(qso: QSO): Promise<number> {
        await this.init();
        return new Promise((resolve, reject) => {
            const transaction = this.db!.transaction(this.storeName, 'readwrite');
            const store = transaction.objectStore(this.storeName);
            const request = store.add(qso);
            request.onsuccess = (e) => resolve((e.target as IDBRequest).result as number);
            request.onerror = (e) => reject((e.target as IDBRequest).error);
        });
    }

    async deleteQSO(id: number): Promise<void> {
        await this.init();
        return new Promise((resolve, reject) => {
            const transaction = this.db!.transaction(this.storeName, 'readwrite');
            const store = transaction.objectStore(this.storeName);
            const request = store.delete(id);
            request.onsuccess = () => resolve();
            request.onerror = (e) => reject((e.target as IDBRequest).error);
        });
    }

    async getAllQSOs(): Promise<QSO[]> {
        await this.init();
        return new Promise((resolve, reject) => {
            const transaction = this.db!.transaction(this.storeName, 'readonly');
            const store = transaction.objectStore(this.storeName);
            const index = store.index('timestamp');
            const request = index.getAll();
            request.onsuccess = (e) => {
                const qsos = (e.target as IDBRequest).result as QSO[];
                // Sort descending (newest first)
                qsos.sort((a, b) => b.timestamp - a.timestamp);
                resolve(qsos);
            };
            request.onerror = (e) => reject((e.target as IDBRequest).error);
        });
    }

    async exportToADIF(): Promise<void> {
        const qsos = await this.getAllQSOs();
        let adif = "Generated by WebFT8 <adif_ver:5>3.1.4 <eoh>\n\n";

        for (const qso of qsos) {
            let row = "";
            const processField = (field: string, value: string | number | undefined) => {
                if (value !== undefined && value !== null && value !== "") {
                    const strVal = String(value);
                    row += `<${field}:${strVal.length}>${strVal} `;
                }
            };

            processField("call", qso.call);
            processField("qso_date", qso.qso_date);
            processField("time_on", qso.time_on);
            processField("band", qso.band);
            processField("freq", qso.freq);
            processField("mode", "FT8");
            processField("rst_sent", qso.rst_sent);
            processField("rst_rcvd", qso.rst_rcvd);
            processField("gridsquare", qso.gridsquare);
            
            row += "<eor>\n";
            adif += row;
        }

        const blob = new Blob([adif], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'webft8_log.adi';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
}

export const logBook = new LogBook();
